---
title: "Data"
format: 
  revealjs:
    slide-number: c/t
    width: 1200
    height: 800
    chalkboard: true
    code-link: true
    code-line-numbers: false
editor: source
engine: knitr
---

## Today

#### Assignment 1:  
#### Assignment 2:  due Tuesday  
#### Assignment 3:  Project proposals  
#### Package installs on Delta:
  - Login to Delta
  - `module load r`
  - `R` starts an interactive R session
  - E.g. to install package `dplyr`:
```{.r}
install.packages("dplyr", repo = "https://cloud.r-project.org/")
```
<br>

#### Delta File Systems
#### Reading data and TLC Data
#### Updated software slides
#### `lapply()`, `mclapply()`


## File Systems on Delta {.incremental}

- Our project name on Delta is `bckj`.

- Each user has access to three file systems `/u/<username>`, `/projects/bckj/<username>`, and `/scratch/bcjk/<username>`  
- See
[Delta: File Systems](https://docs.ncsa.illinois.edu/systems/delta/en/latest/user_guide/architecture.html?highlight=file%20systems#file-systems), and  
[Delta: Data Management](https://docs.ncsa.illinois.edu/systems/delta/en/latest/user_guide/data_mgmt.html) for more details.

- None of the Delta file systems are backed up - another good reason to work via GitHub.

## Permissions on the directories

(`gostrouc` user view):

```{bash}
#| eval: false
#| echo: true
ls -ld $HOME
```

::: {.cell-output-stdout}
```
drwxrwx---+ 9 root root 4096 Mar 29 16:14 /u/gostrouc/
```
:::

```{bash}
#| eval: false
#| echo: true
ls -ld /projects/bckj
```

::: {.cell-output-stdout}
```
drwxrws---+ 26 root delta_bckj 12288 Mar 26 04:55 /projects/bckj/
```
:::

```{bash}
#| eval: false
#| echo: true
ls -ld /scratch/bckj
```

::: {.cell-output-stdout}
```
drwxrws---+ 26 root delta_bckj 8192 Mar 26 04:55 /scratch/bckj/
```
:::
<br>
`d|uuu|ggg|ooo` $\quad$  
dir|user|group|others  

Exec permissions (from `man` page):    
- x   The execute/search bits  
- s   The set-user-ID-on-execution and set-group-ID-on-execution bits  

## `/projects/bcjk`

```{bash}
#| eval: false
#| echo: true
ls -l /projects/bckj
```

::: {.cell-output-stdout}
```
total 96
drwxrws---+ 2 aholme27         delta_bckj 4096 Mar 19 14:55 aholme27/
drwxrws---+ 2 asajjad          delta_bckj 4096 Mar 21 11:55 asajjad/
drwxrws---+ 2 ballred          delta_bckj 4096 Mar 21 10:55 ballred/
drwxrws---+ 2 briddle          delta_bckj 4096 Mar 26 03:55 briddle/
drwxrws---+ 2 carolinetabeling delta_bckj 4096 Mar 21 10:56 carolinetabeling/
drwxrws---+ 2 cdeaton3         delta_bckj 4096 Mar 21 10:55 cdeaton3/
drwxrws---+ 2 cking134         delta_bckj 4096 Mar 19 14:55 cking134/
drwxrws---+ 2 gostrouc         delta_bckj 4096 Feb  3 03:55 gostrouc/
drwxrws---+ 2 hjohns61         delta_bckj 4096 Mar 25 16:55 hjohns61/
drwxrws---+ 2 ianleonard       delta_bckj 4096 Mar 21 10:56 ianleonard/
drwxrws---+ 2 jcamilleri       delta_bckj 4096 Mar 21 10:56 jcamilleri/
drwxrws---+ 2 jgary4           delta_bckj 4096 Mar 21 10:56 jgary4/
drwxrws---+ 2 jmillic4         delta_bckj 4096 Mar 19 14:55 jmillic4/
drwxrws---+ 2 jpeta            delta_bckj 4096 Mar 21 10:55 jpeta/
drwxrws---+ 2 kpatel8          delta_bckj 4096 Mar 21 12:55 kpatel8/
drwxrws---+ 2 lhu7             delta_bckj 4096 Mar 21 10:55 lhu7/
drwxrws---+ 2 lmcpherr         delta_bckj 4096 Mar 21 10:56 lmcpherr/
drwxrws---+ 2 lschwar4         delta_bckj 4096 Mar 19 14:55 lschwar4/
drwxrws---+ 2 mrobiso4         delta_bckj 4096 Mar 26 04:55 mrobiso4/
drwxrws---+ 2 sp28             delta_bckj 4096 Mar 26 03:55 sp28/
drwxrws---+ 2 sthompson2       delta_bckj 4096 Mar 26 04:55 sthompson2/
drwxrws---+ 2 tdykes2          delta_bckj 4096 Mar 21 10:55 tdykes2/
drwxrws---+ 2 wjeter           delta_bckj 4096 Mar 21 10:56 wjeter/
drwxrws---+ 2 ychang27         delta_bckj 4096 Mar 19 14:55 ychang27/
```
:::

## `/scratch/bcjk`

```{bash}
#| eval: false
#| echo: true
ls -l /scratch/bckj
```

::: {.cell-output-stdout}
```
total 96
drwxrws---+ 2 aholme27         delta_bckj 4096 Mar 19 14:55 aholme27/
drwxrws---+ 2 asajjad          delta_bckj 4096 Mar 21 11:55 asajjad/
drwxrws---+ 2 ballred          delta_bckj 4096 Mar 21 10:55 ballred/
drwxrws---+ 2 briddle          delta_bckj 4096 Mar 26 03:55 briddle/
drwxrws---+ 2 carolinetabeling delta_bckj 4096 Mar 21 10:56 carolinetabeling/
drwxrws---+ 2 cdeaton3         delta_bckj 4096 Mar 21 10:55 cdeaton3/
drwxrws---+ 2 cking134         delta_bckj 4096 Mar 19 14:55 cking134/
drwxrws---+ 2 gostrouc         delta_bckj 4096 Feb  3 03:55 gostrouc/
drwxrws---+ 2 hjohns61         delta_bckj 4096 Mar 25 16:55 hjohns61/
drwxrws---+ 2 ianleonard       delta_bckj 4096 Mar 21 10:56 ianleonard/
drwxrws---+ 2 jcamilleri       delta_bckj 4096 Mar 21 10:56 jcamilleri/
drwxrws---+ 2 jgary4           delta_bckj 4096 Mar 21 10:56 jgary4/
drwxrws---+ 2 jmillic4         delta_bckj 4096 Mar 19 14:55 jmillic4/
drwxrws---+ 2 jpeta            delta_bckj 4096 Mar 21 10:55 jpeta/
drwxrws---+ 2 kpatel8          delta_bckj 4096 Mar 21 12:55 kpatel8/
drwxrws---+ 2 lhu7             delta_bckj 4096 Mar 21 10:55 lhu7/
drwxrws---+ 2 lmcpherr         delta_bckj 4096 Mar 21 10:56 lmcpherr/
drwxrws---+ 2 lschwar4         delta_bckj 4096 Mar 19 14:55 lschwar4/
drwxrws---+ 2 mrobiso4         delta_bckj 4096 Mar 26 04:55 mrobiso4/
drwxrws---+ 2 sp28             delta_bckj 4096 Mar 26 03:55 sp28/
drwxrws---+ 2 sthompson2       delta_bckj 4096 Mar 26 04:55 sthompson2/
drwxrws---+ 2 tdykes2          delta_bckj 4096 Mar 21 10:55 tdykes2/
drwxrws---+ 2 wjeter           delta_bckj 4096 Mar 21 10:56 wjeter/
drwxrws---+ 2 ychang27         delta_bckj 4096 Mar 19 14:55 ychang27/
```
:::

## Reading Data Overview
 
- Text files (.csv, .tsv, .txt, ... ): variable length records  
```{.r}
data.table::fread()  # fastest reader
```

```{.r}
readr::read_delim()  # fast reader    
```

- Binary file formats faster for large data (& smaller): fixed length records  
```{.r}
arrow::read_parquet()  # chunked column-oriented format (.parquet extension)
```

  - [Arrow for R Cheatsheet](https://github.com/apache/arrow/blob/main/r/cheatsheet/arrow-cheatsheet.pdf)  
      
```{.r}
rhdf5::h5read()  # hierarchical array-oriented format (.h5 extension)
```

   -  [`rhdf5` Practical Tips](https://bioconductor.org/packages/devel/bioc/vignettes/rhdf5/inst/doc/practical_tips.html) on Bioconductor   

- Other formats (.xlsx, etc. )  
  
## New York TLC Trip Record Data

- [TLC: Taxi and Limousine Commission](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page)  
- Includes: pick-up and drop-off dates/times, pick-up and drop-off locations, trip distances, itemized fares, rate types, payment types, and driver-reported passenger counts

- [Data overview](https://tlcpolicy.maps.arcgis.com/apps/instant/portfolio/index.html?appid=be00fce0963540628e37fd7c75a6d386)  

- [Yellow Trip Data Dictionary](https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf)

- [Green Trips Data Dictionary](https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_green.pdf)  

- [FHV Trips Data Dictionary](https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_fhv.pdf)  

- [High Volume FHV Trips Data Dictionary](https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_hvfhs.pdf)  

## Yellow Trip Data `/projects/bckj/TLC`

```{.r}
cd /projects/bcjk/TLC
ls -l
```

::: {.cell-output-stdout}
```
total 60
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 16:52 2009/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:25 2010/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:26 2011/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:26 2012/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:27 2013/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:27 2014/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:20 2015/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:20 2016/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:21 2017/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:13 2018/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:13 2019/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:06 2020/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:31 2021/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 17:32 2022/
drwxrws---+ 2 gostrouc delta_bckj 4096 Mar 30 22:40 2023/
```
:::

## Yellow Trip Data `/projects/bckj/TLC`

```{.r}
du -h
```

::: {.cell-output-stdout}
```
[gostrouc@dt-login01 TLC]$ du -h .
587M	./2022
1.8G	./2016
458M	./2021
2.0G	./2013
1.4G	./2018
2.1G	./2011
1.2G	./2019
358M	./2020
2.1G	./2012
1.5G	./2017
2.1G	./2014
607M	./2023
5.3G	./2010
1.9G	./2015
5.4G	./2009
29G	.
```
:::

## Yellow Trip Data `2009`

```{.r}
ls -l 2009
```

::: {.cell-output-stdout}
```
total 5583552
-rw-rw----+ 1 gostrouc delta_bckj 469759995 Mar 30 16:51 yellow_tripdata_2009-01.parquet
-rw-rw----+ 1 gostrouc delta_bckj 443434087 Mar 30 16:51 yellow_tripdata_2009-02.parquet
-rw-rw----+ 1 gostrouc delta_bckj 482592227 Mar 30 16:51 yellow_tripdata_2009-03.parquet
-rw-rw----+ 1 gostrouc delta_bckj 478134464 Mar 30 16:51 yellow_tripdata_2009-04.parquet
-rw-rw----+ 1 gostrouc delta_bckj 495321625 Mar 30 16:52 yellow_tripdata_2009-05.parquet
-rw-rw----+ 1 gostrouc delta_bckj 473587848 Mar 30 16:52 yellow_tripdata_2009-06.parquet
-rw-rw----+ 1 gostrouc delta_bckj 454608768 Mar 30 16:52 yellow_tripdata_2009-07.parquet
-rw-rw----+ 1 gostrouc delta_bckj 458271722 Mar 30 16:52 yellow_tripdata_2009-08.parquet
-rw-rw----+ 1 gostrouc delta_bckj 468346719 Mar 30 16:52 yellow_tripdata_2009-09.parquet
-rw-rw----+ 1 gostrouc delta_bckj 527529176 Mar 30 16:52 yellow_tripdata_2009-10.parquet
-rw-rw----+ 1 gostrouc delta_bckj 478304085 Mar 30 16:52 yellow_tripdata_2009-11.parquet
-rw-rw----+ 1 gostrouc delta_bckj 487584891 Mar 30 16:52 yellow_tripdata_2009-12.parquet
```
:::
