---
title: "Assignment 4: Project Data"
editor: source
---

Each Team has chosen a data set for their project. This assignment is to jump start the projects so that each team has a working and fast-readable data set on Delta by the end of this week.

There are team directories `Team1` through `Team6` on the Delta `/project/bckj` file system. 

**Result1:** Download your data set to your `/projects/bckj/Team#` directory, into a subdirectory to keep things organized.

**Result2:** Convert your data set into a `parquet` format, partitioned by a well chosen variable, using the **arrow** package and write it to another subdirectory under `/projects/bckj/Team#`. Good partition size is somewhere between 100 and 500 MB.

**Result3:** Get the sizes of each of the two directories with `du -hs <directory>` and submit the text result of these commands and their output.

The only output to hand in to Canvas are the four lines of Result 3. Of course, the data directories on Delta need to contain the data reported by Result3.

**New:** Result2 is now optional and Result3 requirement is now only two lines.

However for your project (not required for this assignment), you should consider how long it takes to read your data into R and strategies for reducing it. One option is to break up a CSV file into smaller pieces if too big. Timing a single file read versus parallel and smaller reads would decide which is better. Another option is to consider HDF5 format via the [**rhdf5** package](https://bioconductor.org/packages/release/bioc/html/rhdf5.html). If you have many image files, consider organizing them in several directories for parallel treatment across the directories.
